### ISSUE TITLE
Home > Section Notícias

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/copa-america-theme#1]
@matheusgimenez na Home tem esse loop com as 6 últimas notícias, programa por favor PHP, HTML/CSS/Responsivo disso. A single vem em outra issue.

PS. Aproveita o que tem no "dia do graffiti" de CSS ;)

O dev está em BrasaWP/copa.

![_issue](https://cloud.githubusercontent.com/assets/1918474/7562345/2a45315e-f7aa-11e4-8d93-141c6f48df91.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
