### ISSUE TITLE
Home > Section Sobre

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/copa-america-theme#3]
Esse eu iniciei, mas tem apenas o Title. A ideia aqui é trazer o conteúdo da página /sobre com get_page_by_path().

Os três links alí vão funcionar via options-theme, assim como está no "dia do graffiti".

![_issue](https://cloud.githubusercontent.com/assets/1918474/7562512/6f35354c-f7ab-11e4-807d-d7113491105d.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by everaldomatias** [comment]
Vc fez isso com qual options?

No BrasaWP deu uma quebrada, acho que o antigo tava bugado.

**Comment by matheusgimenez** [comment]
Ta no options do que tava no tema mesmo

**Comment by matheusgimenez** [comment]
Pois é.. vi agora.

Podemos substituir por outro.. que tal começarmos com o Kirki nesse?

http://kirki.org

**Comment by everaldomatias** [comment]
Bora de Kirki.
Tenho acompanhado ele no git..
