### ISSUE TITLE
Bug Comentários

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/copa-america-theme#8]
@matheusgimenez depois dá uma olhada nesse bug que está rolando nos comments:

![_copa](https://cloud.githubusercontent.com/assets/1918474/7668840/701e49ba-fc26-11e4-8b76-dd815f77b83f.jpg)

**Comment by everaldomatias** [comment]
@matheusgimenez sobe para a produção, por favor.

**Comment by matheusgimenez** [comment]
Subi
